### Cadastrar um novo modelo
POST https://localhost:5001/ESTACIONAAKI/modelo/create
Content-Type: application/json

{
    "Nome" : "Golf"
}

### Listar todos os modelos
GET https://localhost:5001/ESTACIONAAKI/modelo/list

### Buscar um modelo pelo id
GET https://localhost:5001/ESTACIONAAKI/modelo/getbyid/1

### Deletar um modelo pelo id
DELETE https://localhost:5001/ESTACIONAAKI/modelo/delete/1

### Alterar um modelo
PUT https://localhost:5001/ESTACIONAAKI/modelo/update
Content-Type: application/json

{
    "Id" : 1,
    "nome" : "Bolacha alterada"
}
