### Cadastrar um novo produto
POST https://localhost:5001/ESTACIONAAKI/motorista/create
Content-Type: application/json

{
    "NomeMotorista" : "Joao"
}

### Listar todos os produtos
GET https://localhost:5001/ESTACIONAAKI/motorista/list

### Buscar um produto pelo id
GET https://localhost:5001/ESTACIONAAKI/motorista/getbyid/1

### Deletar um produto pelo nome
DELETE https://localhost:5001/ESTACIONAAKI/motorista/delete/Joao

### Alterar um produto
PUT https://localhost:5001/ESTACIONAAKI/motorista/update
Content-Type: application/json

{
    "Id" : 1,
    "NomeMotorista" : "Bolacha alterada"

}
