### Cadastrar um novo motorista
POST https://localhost:5001/ESTACIONAAKI/motorista/create
Content-Type: application/json

{
    "NomeMotorista" : "oooo"
}

### Listar todos os motoristas
GET https://localhost:5001/ESTACIONAAKI/motorista/list

### Buscar um motorista pelo id
GET https://localhost:5001/ESTACIONAAKI/motorista/getbyid/1

### Deletar um produto pelo nome
DELETE https://localhost:5001/ESTACIONAAKI/motorista/delete/Joao

### Alterar um motorista
PUT https://localhost:5001/ESTACIONAAKI/motorista/update
Content-Type: application/json

{
    "Id" : 1,
    "NomeMotorista" : "Bolacha alterada"

}
